redmine_db_mysql: 89.169.174.117
redmine_db_database: redmine
redmine_db_username: redmine
redmine_port: 3000
redmine_db_password: "{{ vault_redmine_db_password }}"
redmine_db_root_password: "{{ vault_redmine_db_root_password }}"
